FROM centos:7

RUN sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-* \
 && sed -i 's|^#baseurl=http://mirror.centos.org/centos|baseurl=http://vault.centos.org/centos|g' /etc/yum.repos.d/CentOS-*

# glibc-devel provides Scrt1.o, crti.o, crtn.o and the development symlinks for -lc/-lm
RUN yum -y install gcc && yum clean all

ENV PATH="/opt/flang/bin:$PATH"

WORKDIR /work
CMD ["/bin/bash"]
