---
name: build flang for macos (x86_64)

on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/build-macos-x86_64.yml'
  pull_request:
    branches: [master]
    paths:
      - '.github/workflows/build-macos-x86_64.yml'
  workflow_dispatch:
  workflow_call:

jobs:
  build-macos-x86_64:
    runs-on: macos-15-intel
    # runs-on: [self-hosted, macos, x64]
    timeout-minutes: 360
    env:
      SCCACHE_GHA_ENABLED: "true"
      CMAKE_C_COMPILER_LAUNCHER: "sccache"
      CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
      TARGET_TRIPLE: "x86_64-apple-darwin"
      LLVM_VERSION: "21.1.3"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show system information
        run: |
          echo "=== System Information ==="
          echo "CPU cores: $(sysctl -n hw.ncpu)"
          echo "CPU info:"
          sysctl -n machdep.cpu.brand_string
          echo ""
          echo "=== Memory Information ==="
          echo "Total Memory: $(sysctl -n hw.memsize | awk '{print $1/1024/1024/1024 " GB"}')"
          echo ""
          echo "=== Disk Information ==="
          df -h

      - name: Install dependencies
        run: |
          brew install ninja cmake

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Clone LLVM Project
        run: |
          git clone --depth=1 --branch=llvmorg-${{ env.LLVM_VERSION }} \
            https://github.com/llvm/llvm-project.git

      - name: Configure CMake
        run: |
          cmake -S llvm-project/llvm -B build -G Ninja \
                -DLLVM_USE_LINKER="" \
                -DLLVM_PARALLEL_COMPILE_JOBS="" \
                -DLLVM_PARALLEL_LINK_JOBS="" \
                -DLLVM_PARALLEL_TABLEGEN_JOBS="" \
                -DFLANG_PARALLEL_COMPILE_JOBS="" \
                -DCMAKE_OSX_ARCHITECTURES="x86_64" \
                -DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-apple-darwin" \
                -DCMAKE_BUILD_TYPE="MinSizeRel" \
                -DCMAKE_INSTALL_PREFIX="install" \
                -DLLVM_TARGETS_TO_BUILD="host;WebAssembly" \
                -DLLVM_ENABLE_PROJECTS="clang;mlir;flang" \
                -DLLVM_ENABLE_RUNTIMES="compiler-rt;flang-rt;openmp" \
                -DLLVM_INCLUDE_TOOLS=ON \
                -DLLVM_BUILD_TOOLS=OFF \
                -DLLVM_INCLUDE_UTILS=OFF \
                -DLLVM_BUILD_UTILS=OFF \
                -DLLVM_INCLUDE_EXAMPLES=OFF \
                -DLLVM_BUILD_EXAMPLES=OFF \
                -DLLVM_INCLUDE_TESTS=OFF \
                -DLLVM_BUILD_TESTS=OFF \
                -DLLVM_BUILD_LLVM_C_DYLIB=OFF \
                -DLLVM_INCLUDE_DOCS=OFF \
                -DLLVM_BUILD_BENCHMARKS=OFF \
                -DLLVM_INCLUDE_BENCHMARKS=OFF \
                -DLLVM_ENABLE_OCAMLDOC=OFF \
                -DLLVM_ENABLE_BINDINGS=OFF \
                -DLLVM_ENABLE_ZLIB=OFF \
                -DLLVM_ENABLE_ZSTD=OFF \
                -DLLVM_ENABLE_TELEMETRY=OFF \
                -DLLVM_ENABLE_PLUGINS=OFF \
                -DLLVM_INCLUDE_RUNTIMES=ON \
                -DLLVM_BUILD_RUNTIME=OFF \
                -DLLVM_BUILD_RUNTIMES=ON \
                -DLLVM_INSTALL_UTILS=ON \
                -DMLIR_INCLUDE_TESTS=OFF \
                -DFLANG_INCLUDE_TESTS=OFF \
                -DFLANG_INCLUDE_TOOLS=ON \
                -DFLANG_BUILD_TOOLS=OFF \
                -DCLANG_INCLUDE_TESTS=OFF \
                -DCLANG_BUILD_TOOLS=OFF \
                -DCLANG_PLUGIN_SUPPORT=OFF \
                -DCLANG_ENABLE_ARCMT=OFF \
                -DCLANG_ENABLE_STATIC_ANALYZER=OFF \
                -DCLANG_TOOL_APINOTES_TEST_BUILD=OFF \
                -DCLANG_TOOL_CLANG_CHECK_BUILD=OFF \
                -DCLANG_TOOL_CLANG_DIFF_BUILD=OFF \
                -DCLANG_TOOL_CLANG_EXTDEF_MAPPING_BUILD=OFF \
                -DCLANG_TOOL_CLANG_FORMAT_BUILD=OFF \
                -DCLANG_TOOL_CLANG_FUZZER_BUILD=OFF \
                -DCLANG_TOOL_CLANG_IMPORT_TEST_BUILD=OFF \
                -DCLANG_TOOL_CLANG_LINKER_WRAPPER_BUILD=OFF \
                -DCLANG_TOOL_CLANG_NVLINK_WRAPPER_BUILD=OFF \
                -DCLANG_TOOL_CLANG_OFFLOAD_BUNDLER_BUILD=OFF \
                -DCLANG_TOOL_CLANG_OFFLOAD_PACKAGER_BUILD=OFF \
                -DCLANG_TOOL_CLANG_REFACTOR_BUILD=OFF \
                -DCLANG_TOOL_CLANG_REPL_BUILD=OFF \
                -DCLANG_TOOL_CLANG_SCAN_DEPS_BUILD=OFF \
                -DCLANG_TOOL_CLANG_SHLIB_BUILD=OFF \
                -DCLANG_TOOL_C_INDEX_TEST_BUILD=OFF \
                -DCLANG_TOOL_DIAGTOOL_BUILD=OFF \
                -DCLANG_TOOL_DRIVER_BUILD=ON \
                -DCLANG_TOOL_LIBCLANG_BUILD=OFF \
                -DCLANG_TOOL_SCAN_BUILD_BUILD=OFF \
                -DCLANG_TOOL_SCAN_BUILD_PY_BUILD=OFF \
                -DCLANG_TOOL_SCAN_VIEW_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CGDATA_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DEBUGINFO_ANALYZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CTXPROF_UTIL_BUILD=OFF \
                -DLLVM_TOOL_LLVM_REMARKUTIL_BUILD=OFF \
                -DLLVM_TOOL_LLVM_GPU_LOADER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_READTAPI_BUILD=OFF \
                -DLLVM_TOOL_REDUCE_CHUNK_LIST_BUILD=OFF \
                -DLLVM_TOOL_SPIRV_TOOLS_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CONFIG_BUILD=ON \
                -DCLANG_TOOL_CIR_LSP_SERVER_BUILD=OFF \
                -DCLANG_TOOL_CIR_OPT_BUILD=OFF \
                -DCLANG_TOOL_CIR_TRANSLATE_BUILD=OFF \
                -DCLANG_TOOL_CLANG_INSTALLAPI_BUILD=OFF \
                -DCLANG_TOOL_CLANG_SYCL_LINKER_BUILD=OFF \
                -DCLANG_TOOL_OFFLOAD_ARCH_BUILD=OFF \
                -DCPACK_BINARY_NSIS=OFF \
                -DCPACK_SOURCE_7Z=OFF \
                -DCPACK_SOURCE_ZIP=OFF \
                -DLLVM_ENABLE_LIBEDIT=OFF \
                -DLLVM_ENABLE_LIBPFM=OFF \
                -DLLVM_ENABLE_LIBXML2=OFF \
                -DFLANG_PLUGIN_SUPPORT=OFF \
                -DLLVM_TOOL_BUGPOINT_BUILD=OFF \
                -DLLVM_TOOL_BUGPOINT_PASSES_BUILD=OFF \
                -DLLVM_TOOL_CLANG_BUILD=OFF \
                -DLLVM_TOOL_DSYMUTIL_BUILD=OFF \
                -DLLVM_TOOL_DXIL_DIS_BUILD=OFF \
                -DLLVM_TOOL_GOLD_BUILD=OFF \
                -DLLVM_TOOL_LLC_BUILD=OFF \
                -DLLVM_TOOL_LLDB_BUILD=OFF \
                -DLLVM_TOOL_LLI_BUILD=OFF \
                -DLLVM_TOOL_LLVM_AR_BUILD=ON \
                -DLLVM_TOOL_LLVM_AS_BUILD=OFF \
                -DLLVM_TOOL_LLVM_AS_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_BCANALYZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CAT_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CFI_VERIFY_BUILD=OFF \
                -DLLVM_TOOL_LLVM_COV_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CVTRES_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CXXDUMP_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CXXFILT_BUILD=OFF \
                -DLLVM_TOOL_LLVM_CXXMAP_BUILD=OFF \
                -DLLVM_TOOL_LLVM_C_TEST_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DEBUGINFOD_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DEBUGINFOD_FIND_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DIFF_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DIS_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DIS_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DLANG_DEMANGLE_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DWARFDUMP_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DWARFUTIL_BUILD=OFF \
                -DLLVM_TOOL_LLVM_DWP_BUILD=OFF \
                -DLLVM_TOOL_LLVM_EXEGESIS_BUILD=OFF \
                -DLLVM_TOOL_LLVM_EXTRACT_BUILD=OFF \
                -DLLVM_TOOL_LLVM_GSYMUTIL_BUILD=OFF \
                -DLLVM_TOOL_LLVM_IFS_BUILD=OFF \
                -DLLVM_TOOL_LLVM_ISEL_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_ITANIUM_DEMANGLE_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_JITLINK_BUILD=OFF \
                -DLLVM_TOOL_LLVM_JITLISTENER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_LIBTOOL_DARWIN_BUILD=OFF \
                -DLLVM_TOOL_LLVM_LINK_BUILD=OFF \
                -DLLVM_TOOL_LLVM_LIPO_BUILD=OFF \
                -DLLVM_TOOL_LLVM_LTO2_BUILD=OFF \
                -DLLVM_TOOL_LLVM_LTO_BUILD=OFF \
                -DLLVM_TOOL_LLVM_MCA_BUILD=OFF \
                -DLLVM_TOOL_LLVM_MC_ASSEMBLE_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_MC_BUILD=OFF \
                -DLLVM_TOOL_LLVM_MC_DISASSEMBLE_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_MICROSOFT_DEMANGLE_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_ML_BUILD=OFF \
                -DLLVM_TOOL_LLVM_MODEXTRACT_BUILD=OFF \
                -DLLVM_TOOL_LLVM_MT_BUILD=OFF \
                -DLLVM_TOOL_LLVM_NM_BUILD=ON \
                -DLLVM_TOOL_LLVM_OBJCOPY_BUILD=OFF \
                -DLLVM_TOOL_LLVM_OBJDUMP_BUILD=OFF \
                -DLLVM_TOOL_LLVM_OPT_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_OPT_REPORT_BUILD=OFF \
                -DLLVM_TOOL_LLVM_PDBUTIL_BUILD=OFF \
                -DLLVM_TOOL_LLVM_PROFDATA_BUILD=OFF \
                -DLLVM_TOOL_LLVM_PROFGEN_BUILD=OFF \
                -DLLVM_TOOL_LLVM_RC_BUILD=OFF \
                -DLLVM_TOOL_LLVM_READOBJ_BUILD=OFF \
                -DLLVM_TOOL_LLVM_REDUCE_BUILD=OFF \
                -DLLVM_TOOL_LLVM_RTDYLD_BUILD=OFF \
                -DLLVM_TOOL_LLVM_RUST_DEMANGLE_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_SHLIB_BUILD=OFF \
                -DLLVM_TOOL_LLVM_SIM_BUILD=OFF \
                -DLLVM_TOOL_LLVM_SIZE_BUILD=OFF \
                -DLLVM_TOOL_LLVM_SPECIAL_CASE_LIST_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_SPLIT_BUILD=OFF \
                -DLLVM_TOOL_LLVM_STRESS_BUILD=OFF \
                -DLLVM_TOOL_LLVM_STRINGS_BUILD=OFF \
                -DLLVM_TOOL_LLVM_SYMBOLIZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_TLI_CHECKER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_UNDNAME_BUILD=OFF \
                -DLLVM_TOOL_LLVM_XRAY_BUILD=OFF \
                -DLLVM_TOOL_LLVM_YAML_NUMERIC_PARSER_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LLVM_YAML_PARSER_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_LTO_BUILD=OFF \
                -DLLVM_TOOL_OBJ2YAML_BUILD=OFF \
                -DLLVM_TOOL_OPT_BUILD=OFF \
                -DLLVM_TOOL_OPT_VIEWER_BUILD=OFF \
                -DLLVM_TOOL_REMARKS_SHLIB_BUILD=OFF \
                -DLLVM_TOOL_SANCOV_BUILD=OFF \
                -DLLVM_TOOL_SANSTATS_BUILD=OFF \
                -DLLVM_TOOL_VERIFY_USELISTORDER_BUILD=OFF \
                -DLLVM_TOOL_VFABI_DEMANGLE_FUZZER_BUILD=OFF \
                -DLLVM_TOOL_XCODE_TOOLCHAIN_BUILD=OFF \
                -DLLVM_TOOL_YAML2OBJ_BUILD=OFF

      - name: Build
        run: |
          cmake --build build --config MinSizeRel

      - name: Install
        run: |
          cmake --install build --config MinSizeRel

      - name: Show sccache statistics
        run: |
          echo "=== sccache Statistics ==="
          sccache --show-stats

      - name: Prepare distribution package
        run: |
          cmake -P install-x86_64-apple-darwin.cmake

      - name: Package binaries
        run: |
          tar -czf flang+llvm-${{ env.LLVM_VERSION }}-${{ env.TARGET_TRIPLE }}.tar.gz dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flang+llvm-${{ env.LLVM_VERSION }}-${{ env.TARGET_TRIPLE }}
          path: flang+llvm-${{ env.LLVM_VERSION }}-${{ env.TARGET_TRIPLE }}.tar.gz
          retention-days: 30
